#! /bin/sh


# Set the left cursor to fix black X cursor on desktop
xsetroot -cursor_name left_ptr

sxhkd &

xset r rate 250 50
setxkbmap -option caps:escape

# Reload last color theme
settheme -R
# Reload the last used background
setbg -R

# Set the border color according to the set theme

# Randomize the background image
randbg

dunst &

killall -q picom
picom &

killall -q polybar
polybar bar &
pulseaudio &

# Set primary monitor
xrandr --output HDMI-0 --primary --left-of DVI-D-0

# Focus follows mouse
bspc config focus_follows_pointer false

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap           6
bspc config top_padding          24 

bspc config split_ratio          0.618
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Remove all rules first
bspc rule -r *:*

bspc rule -a Thunar state=floating
bspc rule -a Nemo state=floating
bspc rule -a mpv state=floating
bspc rule -a Gimp-2.10 desktop='^4' state=floating follow=on
# bspc rule -a firefox desktop='^3' follow=on
# bspc rule -a qutebrowser desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating
bspc rule -a Blender state=floating
bspc rule -a Code monitor=HDMI-0
bspc rule -a discord monitor=HDMI-1, state=floating
bspc rule -a spotify desktop='^2' follow=off

bspc rule -a Lxtask state=floating
bspc rule -a Pavucontrol state=floating

# Steam and games
bspc rule -a Steam desktop='^6' follow=off
bspc rule -a 'Minecraft*' desktop='^5' follow=off
bspc rule -a csgo_linux64 desktop='^5' follow=off
bspc rule -a Equilinox desktop='^5' follow=off
bspc rule -a TerraTech desktop='^5' follow=off
bspc rule -a Unturned desktop='^5' follow=off
bspc rule -a factorio desktop='^5' follow=off
bspc rule -a Plank layer=above manage=on border=off
# Autostart
#killall spotify
#spotify &
killall ckb-next
ckb-next -b
